let shopItemsData = [
    {
      id: "redroses",
      name: "red roses",
      price: 15,
      desc: "the most beautiful red roses.",
      img: "images/redrose2.jpg",
    },
    {
      id: "yellowroses",
      name: "yellow roses",
      price: 12,
      desc: "have a nice day with yellow roses.",
      img: "images/yellow.jpg",
    },
    {
      id: "pinkroses",
      name: "pink roses",
      price: 12,
      desc: "pink roses for the right occation.",
      img: "images/pinkroses.jpg",
    },
    {
      id: "mixcombos",
      name: "Mix roses",
      price: 18,
      desc: "red,pink,yellow,and white roses.",
      img: "images/mixroses.jpg",
    },
    {
      id: "thiecbawdjksadjk",
      name: "combos",
      price: 24,
      desc: "1/2 a dozen roses of your choice(up to three).",
      img: "images/comboroses.jpg",
    },
    {
      id: "bouquet",
      name: "bouquet",
      price: 21,
      desc: "roses,flowers,bow and a lil extra.",
      img: "images/bouquet.jpg",
    },
    {
      id: "diamon",
      name: "diamon special",
      price: 30,
      desc: "A lil of everything and some more.",
      img: "images/diamonspecial.jpg",
    },
    {
      id: "custom",
      name: "custom",
      price: 45,
      desc: "tell us what you want and we got it for you.",
      img: "images/youbuild.jpg",
    },
    {
      id: "events",
      name: "events",
      price: 800,
      desc: "meetings,gatherings,and dinners.",
      img: "images/event1.jpg",
    },
    {
      id: "weddings",
      name: "weddings",
      price: 1200,
      desc: "its your wedding! lets make it special.",
      img: "images/events.jpg",
    },
    {
      id: "design",
      name: "designs",
      price: 12,
      desc: "lets make a custom photo,card, or flyer.",
      img: "images/design.jpg",
    },
    {
      id: "delivery",
      name: "special delivery",
      price: 8,
      desc: "we will deliver it for you... new york city only.",
      img: "images/delivery.jpg",
    },
  ];